=== dmarcato/bazingarent/xml/lista.dtd
<!ELEMENT lista (film+)>
<!ELEMENT film (titolo,regista,cast,genere,uscita,descrizione,image,data,link,disp,noleggi)>
<!ATTLIST film id ID #REQUIRED>
<!ELEMENT titolo (#PCDATA)>
<!ELEMENT regista (#PCDATA)>
<!ELEMENT cast (#PCDATA)>
<!ELEMENT genere (#PCDATA)>
<!ELEMENT uscita (#PCDATA)>
<!ELEMENT descrizione (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT data (anno,mese,giorno)>
<!ELEMENT anno (#PCDATA)>
<!ELEMENT mese (#PCDATA)>
<!ELEMENT giorno (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT disp (#PCDATA)>
<!ELEMENT noleggi (#PCDATA)>

=== dmarcato/bazingarent/xml/film.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE lista SYSTEM "./BazingaRent/xml/lista.dtd">

<lista>
	<film id="01">
		<titolo>Prince of Persia - Le sabbie del tempo</titolo>
    	<regista>Mike Newell</regista>
    	<cast>Jake Gyllenhaal, Ben Kingsley, Gemma Arterton, Alfred Molina, Steve Toussaint</cast>
    	<genere>Azione</genere>
		<uscita>2010</uscita>
		<descrizione>Ambientato nella Persia medievale, il film racconta la storia di un principe avventuroso che fa coppia con la principessa rivale per fermare un sovrano arrabbiato che vuole scatenare una tempesta di sabbia che pu&ograve; distruggere il mondo...</descrizione>
    	<image>http://www.mymovies.it/filmclub/2007/03/167/locandina.jpg</image>
		<data>
			<anno>--</anno>
			<mese>--</mese>
			<giorno>--</giorno>
		</data>
		<link>http://www.mymovies.it/film/2010/princeofpersialesabbiedeltempo/</link>
		<disp>--</disp>
		<noleggi>--</noleggi> 
	</film>
	
	<film id="02">
		<titolo>Alice in Wonderland</titolo>
    	<regista>Tim Burton</regista>
    	<cast>Mia Wasikowska, Johnny Depp, Helena Bonham Carter, Crispin Glover, Anne Hathaway</cast>
		<genere>Fantastico</genere>
		<uscita>2010</uscita>
		<descrizione>Alice ha diciassette anni e scappa da un party altezzoso e segue il Bianconiglio gi&ugrave; per il buco, che la riporta nuovamente al Paese delle Meraviglie. Il Bianconiglio &egrave; convinto di avere la ragazza giusta, quella che ha visitato il magico mondo...</descrizione>
    	<image>http://www.mymovies.it/filmclub/2008/06/094/locandina.jpg</image>
		<data>
			<anno>2010</anno>
			<mese>04</mese>
			<giorno>19</giorno>
		</data>
		<link>http://www.mymovies.it/film/2010/aliceinwonderland/</link>
		<disp>03</disp>
		<noleggi>25</noleggi>
	</film>
		
	<film id="03">
		<titolo>Scusa ma ti voglio sposare</titolo>
    	<regista>Federico Moccia</regista>
    	<cast>Raoul Bova, Michela Quattrociocche, Luca Angeletti, Francesca Antonelli, Francesco Apolloni</cast>
		<genere>Sentimentale</genere>
		<uscita>2010</uscita>
		<descrizione>Sequel della storia targata Moccia Scusa ma ti chiamo amore. Dopo tre anni, Alex capisce che nonostante la differenza di et&agrave;, Niki &egrave; la donna che vuole sposare. Ritroviamo i loro amici di sempre, ognuno con le proprie storie, ognuno con le proprie attivit&agrave;...</descrizione>
    	<image>http://www.mymovies.it/filmclub/2008/11/114/locandina.jpg</image>
		<data>
			<anno>2010</anno>
			<mese>03</mese>
			<giorno>28</giorno>
		</data>
		<link>http://www.mymovies.it/film/2010/scusamativogliosposare/</link>
		<disp>05</disp>
		<noleggi>20</noleggi>
	</film>
	
	<film id="04">
		<titolo>Scontro tra Titani</titolo>
    	<regista>Louis Leterrier</regista>
    	<cast>Sam Worthington, Liam Neeson, Ralph Fiennes, Gemma Arterton, Mads Mikkelsen</cast>
		<genere>Avventura</genere>
		<uscita>2010</uscita>
		<descrizione>La battaglia finale per il potere ha messo gli uomini contro i re e i re contro gli dei, ma la guerra tra gli dei stessi potrebbe distruggere il mondo. Nato da un dio ma cresciuto come un uomo, Perseo &egrave; inerme nel salvare la sua famiglia da Hades...</descrizione>
    	<image>http://www.mymovies.it/filmclub/2009/04/066/locandina.jpg</image>
		<data>
			<anno>--</anno>
			<mese>--</mese>
			<giorno>--</giorno>
		</data>
		<link>http://www.mymovies.it/film/2010/scontrotratitani/</link>
		<disp>--</disp>
		<noleggi>--</noleggi>
	</film>
	
	<film id="05">
		<titolo>Iron Man 2</titolo>
    	<regista>Jon Favreau</regista>
    	<cast>Robert Downey Jr., Gwyneth Paltrow, Don Cheadle, Scarlett Johansson, Sam Rockwell</cast>
		<genere>Azione</genere>
		<uscita>2010</uscita>
		<descrizione>In "Iron Man 2," il mondo &egrave; consapevole che il miliardario inventore Tony Stark (Robert Downey Jr.) &egrave; il corazzato supereroe Iron Man. Sotto pressione da parte del governo, la stampa e il pubblico per condividere la sua...</descrizione>
    	<image>http://www.mymovies.it/filmclub/2008/12/128/locandina.jpg</image>
		<data>
			<anno>--</anno>
			<mese>--</mese>
			<giorno>--</giorno>
		</data>
		<link>http://www.mymovies.it/film/2010/ironman2/</link>
		<disp>--</disp>
		<noleggi>--</noleggi>
	</film>
	
	<film id="06">
		<titolo>Wolfman</titolo>
    	<regista>Joe Johnston</regista>
    	<cast>Benicio Del Toro, Anthony Hopkins, Emily Blunt, Hugo Weaving, Art Malik</cast>
		<genere>Horror</genere>
		<uscita>2010</uscita>
		<descrizione>L'infanzia di Talbot &egrave; finita la morte in cui la madre &egrave; morta. Dopo aver lasciato il paesino addormentato Vittoriano di Blackmoor, ha passato decenni per riprendersi e cercare di dimenticare. Ma quando la fidanzata di suo fratello, Gwen Conliffe...</descrizione>
    	<image>http://www.mymovies.it/filmclub/2008/03/077/locandina.jpg</image>
		<data>
			<anno>--</anno>
			<mese>--</mese>
			<giorno>--</giorno>
		</data>
		<link>http://www.mymovies.it/film/2010/thewolfman/</link>
		<disp>--</disp>
		<noleggi>--</noleggi>
	</film>
	
	<film id="07">
		<titolo>Shutter Island</titolo>
    	<regista>Martin Scorsese</regista>
    	<cast>Leonardo DiCaprio, Mark Ruffalo, Ben Kingsley, Michelle Williams, Patricia Clarkson</cast>
		<genere>Drammatico</genere>
		<uscita>2010</uscita>
		<descrizione>Niente &egrave; quello che sembra all'Ashecliffe Hospital. E nemmeno lo &egrave; Teddy Daniels. E' l&igrave; per trovare un paziente che manca? O &egrave; stato mandato per investigare sui rumor riguardanti gli approcci radicali verso la psichiatria attuati...</descrizione>
    	<image>http://www.mymovies.it/filmclub/2009/03/099/locandina.jpg</image>
		<data>
			<anno>2010</anno>
			<mese>05</mese>
			<giorno>18</giorno>
		</data>
		<link>http://www.mymovies.it/film/2010/shutterisland/</link>
		<disp>02</disp>
		<noleggi>06</noleggi>
	</film>
	
	<film id="08">
		<titolo>Baciami ancora</titolo>
    	<regista>Gabriele Muccino</regista>
    	<cast>Stefano Accorsi, Vittoria Puccini, Pierfrancesco Favino, Claudio Santamaria, Giorgio Pasotti</cast>
		<genere>Drammatico</genere>
		<uscita>2010</uscita>
		<descrizione>Uno sguardo, dieci anni dopo, alle vite di Carlo e Giulia, protagonisti de L'ultimo bacio. La storia si svolge a Roma, dieci anni dopo il primo episodio, e narra l'evoluzione della storia d'amore dei due protagonisti, le loro vite e quelle dei loro amici di...</descrizione>
    	<image>http://www.mymovies.it/filmclub/2009/06/055/locandina.jpg</image>
		<data>
			<anno>2010</anno>
			<mese>04</mese>
			<giorno>30</giorno>
		</data>
		<link>http://www.mymovies.it/film/2010/baciamiancora/</link>
		<disp>01</disp>
		<noleggi>18</noleggi>
	</film>
	
	<film id="09">
		<titolo>Avatar</titolo>
    	<regista>James Cameron</regista>
    	<cast>Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang, Michelle Rodriguez</cast>
		<genere>Fantascienza</genere>
		<uscita>2009</uscita>
		<descrizione>Avatar ci porta in un mondo nuovo e spettacolare al di l&agrave; di ogni immaginazione, dove un eroe ribelle si imbarca in un’avventura epica, che alla fine lo vedr&agrave; combattere per salvare il mondo alieno che ha imparato a chiamare casa. Il film era...</descrizione>
    	<image>http://www.mymovies.it/filmclub/2008/03/090/locandina.jpg</image>
		<data>
			<anno>2010</anno>
			<mese>04</mese>
			<giorno>02</giorno>
		</data>
		<link>http://www.mymovies.it/film/2009/avatar/</link>
		<disp>0</disp>
		<noleggi>37</noleggi>
	</film>
	
	<film id="10">
		<titolo>Harry Potter e il principe mezzosangue</titolo>
    	<regista>David Yates</regista>
    	<cast>Daniel Radcliffe, Emma Watson, Rupert Grint, Michael Gambon, Alan Rickman</cast>
		<genere>Fantastico</genere>
		<uscita>2009</uscita>
		<descrizione>Voldemort allunga la sua ombra minacciosa sia sul mondo dei Babbani che su quello dei maghi e Hogwarts non &egrave; pi&ugrave; un posto sicuro e accogliente come in passato. Harry sospetta che i pericoli minacciano anche la scuola, ma Silente concentra la sua...</descrizione>
    	<image>http://www.mymovies.it/filmclub/2007/02/129/locandina.jpg</image>
		<data>
			<anno>2010</anno>
			<mese>02</mese>
			<giorno>02</giorno>
		</data>
		<link>http://www.mymovies.it/film/2009/harrypotter6/</link>
		<disp>02</disp>
		<noleggi>12</noleggi>
	</film>
	
	<film id="11">
		<titolo>Angeli e Demoni</titolo>
    	<regista>Ron Howard</regista>
    	<cast>Tom Hanks, Ewan McGregor, Ayelet Zurer, Stellan Skarsgård, Pierfrancesco Favino</cast>
		<genere>Thriller</genere>
		<uscita>2009</uscita>
		<descrizione>Langdon scopre le prove della rinascita di unantica confraternita segreta conosciuta come gli Illuminati, la pi&ugrave; potente organizzazione sotto copertura della Storia, e deve anche fronteggiare un pericolo mortale per la sopravvivenza del nemico pi&ugrave;...</descrizione>
    	<image>http://www.mymovies.it/filmclub/2008/10/022/locandina.jpg</image>
		<data>
			<anno>2009</anno>
			<mese>11</mese>
			<giorno>09</giorno>
		</data>
		<link>http://www.mymovies.it/dizionario/recensione.asp?id=46904</link>
		<disp>04</disp>
		<noleggi>16</noleggi>
	</film>
	
	<film id="12">
		<titolo>L'era glaciale 3 - L'alba dei dinosauri</titolo>
    	<regista>Carlos Saldanha</regista>
    	<cast>Ray Romano, John Leguizamo, Denis Leary, Simon Pegg, Queen Latifah</cast>
		<genere>Animazione</genere>
		<uscita>2009</uscita>
		<descrizione>Dopo gli eventi del secondo film, la vita comincia a cambiare per Manny e i suoi amici: Scrat &egrave; ancora alla caccia della sua amata ghianda, ma trova una possibile storia d'amore con la scoiattola Scratte. Manny e Ellie sono diventati una coppia e stanno...</descrizione>
    	<image>http://www.mymovies.it/filmclub/2008/03/061/locandina.jpg</image>
		<data>
			<anno>2009</anno>
			<mese>12</mese>
			<giorno>15</giorno>
		</data>
